import { API_BASE, authHeaders } from '@/lib/utils'

/**
 * Convert a URL-safe Base64 string to a Uint8Array for PushManager subscription.
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/')

  const rawData = window.atob(base64)
  const outputArray = new Uint8Array(rawData.length)

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i)
  }
  return outputArray
}

export function isPushNotificationSupported(): boolean {
  if (typeof window === 'undefined') return false
  return (
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  )
}

export function isIOS(): boolean {
  if (typeof window === 'undefined') return false
  return /iPad|iPhone|iPod/.test(navigator.userAgent) || 
    (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)
}

export function isStandalone(): boolean {
  if (typeof window === 'undefined') return false
  return (
    (window.navigator as unknown as { standalone?: boolean }).standalone === true ||
    window.matchMedia('(display-mode: standalone)').matches
  )
}

export function getNotificationPermission(): NotificationPermission {
  if (typeof window === 'undefined' || !('Notification' in window)) {
    return 'default'
  }
  return Notification.permission
}

/**
 * Check if the current device/browser is already subscribed to push notifications.
 */
export async function isCurrentDeviceSubscribed(): Promise<boolean> {
  if (!isPushNotificationSupported()) return false
  try {
    const reg = await navigator.serviceWorker.ready
    const sub = await reg.pushManager.getSubscription()
    return !!sub
  } catch {
    return false
  }
}

/**
 * Request notification permission, register with Apple/Google push servers,
 * and sync subscription with the MyTally backend.
 */
export async function subscribeToPushNotifications(
  token: string
): Promise<{ success: boolean; message: string }> {
  if (!isPushNotificationSupported()) {
    if (isIOS() && !isStandalone()) {
      return {
        success: false,
        message: 'On iPhone, please tap Share -> "Add to Home Screen" first to enable notifications.'
      }
    }
    return {
      success: false,
      message: 'Push notifications are not supported by this browser.'
    }
  }

  try {
    // 1. Request permission
    const permission = await Notification.requestPermission()
    if (permission !== 'granted') {
      return {
        success: false,
        message: permission === 'denied' 
          ? 'Notification permission was denied. Please allow notifications in device settings.'
          : 'Notification permission was dismissed.'
      }
    }

    // 2. Ensure Service Worker is ready
    const reg = await navigator.serviceWorker.ready

    // 3. Fetch VAPID public key
    const vapidRes = await fetch(`${API_BASE}/notifications/vapid-public-key`, {
      headers: authHeaders(token)
    })
    if (!vapidRes.ok) {
      throw new Error('Failed to retrieve push encryption key from server.')
    }
    const { public_key } = await vapidRes.json()
    if (!public_key) {
      throw new Error('VAPID public key missing from server response.')
    }

    // 4. Subscribe to PushManager
    const applicationServerKey = urlBase64ToUint8Array(public_key)
    let subscription = await reg.pushManager.getSubscription()
    
    if (!subscription) {
      subscription = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        // Passing applicationServerKey as ArrayBuffer or Uint8Array
        applicationServerKey: applicationServerKey as unknown as ArrayBuffer
      })
    }

    const subJson = subscription.toJSON()
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      throw new Error('Invalid push subscription generated by browser.')
    }

    // 5. Send subscription to MyTally backend
    const saveRes = await fetch(`${API_BASE}/notifications/subscribe`, {
      method: 'POST',
      headers: {
        ...authHeaders(token),
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        endpoint: subJson.endpoint,
        keys: {
          p256dh: subJson.keys.p256dh,
          auth: subJson.keys.auth
        },
        user_agent: typeof navigator !== 'undefined' ? navigator.userAgent.slice(0, 255) : null
      })
    })

    if (!saveRes.ok) {
      const err = await saveRes.json().catch(() => ({}))
      throw new Error(err.detail || 'Failed to save push subscription on server.')
    }

    return {
      success: true,
      message: 'Mobile push notifications enabled! You will now receive alerts even when your phone is locked.'
    }
  } catch (err: unknown) {
    console.error('[PushNotifications] Subscription error:', err)
    return {
      success: false,
      message: err instanceof Error ? err.message : 'An error occurred while enabling push notifications.'
    }
  }
}

/**
 * Unsubscribe current device from push notifications.
 */
export async function unsubscribeFromPushNotifications(
  token: string
): Promise<{ success: boolean; message: string }> {
  try {
    if (!isPushNotificationSupported()) return { success: true, message: 'Not supported' }
    const reg = await navigator.serviceWorker.ready
    const sub = await reg.pushManager.getSubscription()
    if (sub) {
      const endpoint = sub.endpoint
      await sub.unsubscribe()
      await fetch(`${API_BASE}/notifications/unsubscribe`, {
        method: 'POST',
        headers: {
          ...authHeaders(token),
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ endpoint })
      }).catch(() => null)
    }
    return { success: true, message: 'Push notifications disabled on this device.' }
  } catch (err) {
    console.error('[PushNotifications] Unsubscribe error:', err)
    return { success: false, message: 'Failed to disable push notifications.' }
  }
}

/**
 * Send an immediate test notification to verify device alerts.
 */
export async function sendTestPushNotification(
  token: string
): Promise<{ success: boolean; message: string; devices_notified?: number }> {
  try {
    const res = await fetch(`${API_BASE}/notifications/test-push`, {
      method: 'POST',
      headers: authHeaders(token)
    })
    const data = await res.json()
    return data
  } catch {
    return { success: false, message: 'Network error sending test push notification.' }
  }
}
